services:

  reverse_proxy:
    container_name: reverse_proxy
    image: nginx:1.29
    volumes:
      - ./web:/usr/share/nginx/html
      - ./default.config:/etc/nginx/conf.d/default.conf
    ports:
      - 81:81
    networks:
      - web_network
    depends_on:
      - api

  database:
    container_name: database
    image: mongo:6.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - TZ=America/Sao_Paulo
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./backup_dev:/data/db:rw
    networks:
      - database_network

  api:
    container_name: api
    image: node:23.8.0
    environment:
      - EXPRESS_PORT=2000
      - NODE_ENV=dev
      - MONGO_USER=master
      - MONGO_PASSWORD=123qwe
      - MONGO_DATABASE=catalogDB
    networks:
      - web_network
      - database_network
    volumes:
      - ./api:/api:rw
      - ./keys/:/keys:rw
    working_dir: /api
    command: bash -c "npm install && npm run dev"
    depends_on:
      - database
      - whitelist

  whitelist:
    container_name: whitelist
    image: redis:8.0
    networks:
      - database_network

networks:
  web_network:
    name: web_network
  database_network:
    name: database_network
  