services:
  database:
    container_name: database
    image: mongo:6.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - TZ=America/Sao_Paulo
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./backup_dev:/data/db:rw

  api:
    container_name: api
    image: node:23.8.0
    environment:
      - EXPRESS_PORT=2000
      - NODE_ENV=dev
      - MONGO_USER=master
      - MONGO_PASSWORD=123qwe
      - MONGO_DATABASE=catalogDB
    volumes:
      - ./api:/api:rw
      - ./keys/:/keys:rw
    ports:
      - 2000:2000
    working_dir: /api
    command: bash -c "npm install && npm run dev"
    depends_on:
      - database
      - whitelist

  whitelist:
    container_name: whitelist
    image: redis:8.0
    ports:
      - 6379:6379


## Run application
#docker compose -f docker-compose.dev.yaml up
