services:

  database:
    container_name: database
    image: mongo:6.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - TZ=America/Sao_Paulo
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  api:
    container_name: api
    image: node:23.8.0
    environment:
      - EXPRESS_PORT=2000
      - NODE_ENV=test
      - MONGO_USER=master
      - MONGO_PASSWORD=123qwe
      - MONGO_DATABASE=catalogDB
      - NODE_OPTIONS=$NODE_OPTIONS --experimental-vm-modules
      - NODE_ENV=test
    volumes:
      - ./api:/api:rw
      - ./logs:/logs:rw
      - ./keys/:/keys:rw
      - ./jest.config.js:/jest.config.js:ro

    ports:
      - 2000:2000
    working_dir: /api
    command: bash -c "npm install && npm test"
    depends_on:
      - database
      - whitelist

  whitelist:
    container_name: whitelist
    image: redis:8.0
